databases:
  - name: render_site
    databaseName: render_site
    user: render_site

services:
  - type: web
    name: render_site
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_site
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
